package Funciones;

import java.util.Arrays;
import java.util.Iterator;
import java.util.List;
import javax.swing.ImageIcon;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JRSaveContributor;
public class MostrarReporte extends javax.swing.JDialog {

    private final String PDF = "PDF (*.pdf)";
    private final List<String> PERMITTED_FILE_TYPES_LIST = Arrays.asList(this.PDF);

    public MostrarReporte(java.awt.Frame parent, boolean modal, JasperPrint print, String nombre) {
        super(parent, modal);
        initComponents();

        reporteCustom viewer = new reporteCustom(print);
        viewer.setNombre(nombre);
        viewer.setSize(835, 613);
        viewer.setZoomRatio(0.6544f);

        List<JRSaveContributor> saveOptions = Arrays.asList(viewer.getSaveContributors());
        Iterator<JRSaveContributor> i = saveOptions.iterator();

        while (i.hasNext()) {
            JRSaveContributor jsc = i.next();
            if (PERMITTED_FILE_TYPES_LIST.contains(jsc.getDescription())) {
                continue;
            } else {
                viewer.removeSaveContributor(jsc);
            }
        }
        this.setTitle("Vista preliminar reporte");
        this.setIconImage(new ImageIcon(getClass().getResource("/img/logo.jpg")).getImage());
        this.setAlwaysOnTop(false);
        this.setLocationRelativeTo(null);
        viewer.setVisible(true);
        this.add(viewer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 835, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        
    // Variables declaration - do not modify                     
    // End of variables declaration                   
}